### ISSUE TITLE
deeppy is missing

### ISSUE THREAD

**Issue by davidbp** [DTU-deeplearning/day2-Conv#1]
When trying to import the preliminaries of the ipython notebook convnet_exercise.ipynb the line " import deeppy as dp" breaks.
Is there any deeppy.py file missing in the folder?

**Comment by casperkaae** [comment]
You can install deeppy by

git clone git@github.com:andersbll/deeppy.git
cd deeppy
python setup.py install

You won't need deeppy for the exercise though

**Comment by davidbp** [comment]
thanks
